; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform = atmelavr
board = uno
framework = arduino
; monitor_speed = 115200 ; test to make sure this works tbh
monitor_speed = 57600 ; test to make sure this works tbh

; -Oz for super aggressive size optimization;
build_flags = -Wno-unknown-pragmas -Os
 
[env:main]
build_src_filter = +<main.cpp>

[env:test]
build_src_filter = +<test.cpp>


; [env:part2]
; build_src_filter = +<bdeng021_lab7_part2.cpp>


; [env:part3]
; build_src_filter = +<bdeng021_lab7_part3.cpp>
